### PR TITLE
Add linkedin support. Add more settings.

### PR DESCRIPTION
**Pull request by simonoff**
- Added support for linkedin
- Added support for hiding "Share" button when we will show buttons all time
- Added support for not hiding buttons after clicking on one of them
- Small refactoring of code

### CODE REVIEW

**Comment by jenius** [comment]
Screenshot/gif?

**Comment by hhsnopek** [comment]
Here it is!
gif of linkedin addition

**Comment by jenius** [comment]
This looks pretty good to me. @tmilewski thoughts? Also do we have support for enabling/disabling specific networks? the number of buttons here is getting pretty high

**Comment by hhsnopek** [comment]
@jenius there is a way to disable buttons within the config, they're just all enabled by default :)

**Comment by NetanelBasal** [comment]
You can add update the configuration file for this new networks please?

**Comment by hhsnopek** [comment]
closed via df81f5cbe2c992949842b508d3a3b3a4ba6c3a5f

**Pull request closed without merging**
