### PR TITLE
Add VK.com

### PR DESCRIPTION
**Pull request by VyacheslavAlexeev**

### CODE REVIEW

**Comment by hhsnopek** [comment]
Hey @VyacheslavAlexeev, Glad you're contributing to the share button! Would you be able to add tests, minify the svg, add the styles to the stylus file and upload a screenshot to this PR for us to see?

**Comment by VyacheslavAlexeev** [comment]
Excuse me in advance for those unnecessary commits but when I do test with `npm test` it fails with an error :
```
Feature: Collision Detection   # tests/features/animation.feature

@animation
Scenario: Classes will be porperly adjusted according to Share Button position
/Users/vyacheslav/dev/share-button/node_modules/pioneer/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:39
goog.global.setTimeout(function() { throw exception; }, 0);

Error: The PhantomJS executable could not be found on the current PATH. Please download the latest version from http://phantomjs.org/download.html and ensure it can be found on your PATH. For more information, see https://github.com/ariya/phantomjs/wiki
```

**Comment by VyacheslavAlexeev** [comment]
![Preview]
(https://leto29f.storage.yandex.net/rdisk/f01337bd98a647298b7790743934b3d21b5b8d144cd845b0d9bb25d5c2c14fe6/inf/iRUGtxaUy1FMjWLpbt--8b8hBC44FM2fS8gn-T6cMf8yV19PLx5-EWXpD6575NnIUKNlQBvvo-21d75nC1d_zg==?uid=0&filename=2015-10-28%2016-03-58%20Share%20Button%20Test.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=9eb7658500ec1aaa611662bc7eab767c&force_default=no&ycrid=na-53a006b2871b6aa2f0de10bd8b15aa8f-downloader8d)

**Comment by hhsnopek** [comment]
@VyacheslavAlexeev  It seems you don't have phantomjs installed or it's not properly available for pioneer.js to grab, the last line in your error log will guide you on how to install or debug the `path` to phantomjs

**Comment by VyacheslavAlexeev** [comment]
All of the tests passed. Do you want to accept my PR?

**Comment by hhsnopek** [comment]
I'll need to review it at some point then I will :) 



--
Henry Snopek

**Comment by hhsnopek** [comment]
If I get time tonight I'll get this reviewed and merged in. Sorry for the delay, busy weekend!

**Comment by VyacheslavAlexeev** [comment]
Thanks!

**Comment by VyacheslavAlexeev** [comment]
Don't forget about me ;3

**Comment by hustKiwi** [comment]
@hhsnopek Just reminding, hope you can merge this:)

**Comment by VyacheslavAlexeev** [comment]
lol

**Pull request closed without merging**
