### PR TITLE
Add linkedin network. Closes #96

### LINKED ISSUE #96: Linked In?
Possible to add linked in?

### PR DESCRIPTION
**Pull request by ecancino**

### CODE REVIEW

**Comment by treeskelt** [comment]
@jenius Is there any ETA on the merge/feedback on these pull requests?

**Comment by jenius** [comment]
Hi @treeskelt -- I'm really sorry but I'm traveling for an extended period of time at the moment and am not able to continue being vigilant with maintenance for this library until I get back. Perhaps someone else from @carrot/devs would be able to help out!

**Comment by treeskelt** [comment]
@jenius thanks,
@carrots Hi, anybody?

**Comment by hhsnopek** [comment]
I just cloned this down, everything seems to be working properly
:+1: for merging

**Comment by hhsnopek** [comment]
closed via https://github.com/carrot/share-button/commit/7ab33b83d3ae1a7bd53e9e125d4acedc075f63b4

**Pull request closed without merging**
