### PR TITLE
v1.0.0 es6

### PR DESCRIPTION
**Pull request by hhsnopek**
Convert coffee to es6

### CODE REVIEW

**Comment by hhsnopek** [comment]
Rebasing into one commit - functionality of the share-button is working. Time to get the styles working!

**Comment by hhsnopek** [comment]
cc @kylemac @tmilewski

**Comment by hhsnopek** [comment]
locally we've fixed the styles as well

**Comment by tmilewski** [comment]
Mind adding instructions for building the `dist` files?

**Comment by hhsnopek** [comment]
yeah - I'm going to push the rebased version up with the other changes

**Comment by hhsnopek** [comment]
before this gets merged, I'm going to add documentation

**Comment by kylemac** [comment]
@hhsnopek made this [wip] and just remove and ping @tmilewski when its ready to be reviewed/merged

**Comment by hhsnopek** [comment]
:+1: thank you

**Comment by hhsnopek** [comment]
This is ready, pending #171 @tmilewski

**Pull request merged**
