### PR TITLE
Fixes Issues #305 & #304

### PR DESCRIPTION
**Pull request by erwstout**
## Description

Fixes Issues https://github.com/carrot/share-button/issues/305 & https://github.com/carrot/share-button/issues/304 to allow successful `npm install` and Chrome svg issues.
### PR Checklist
- [x] [Clean commits](https://github.com/carrot/share-button/blob/master/CONTRIBUTING.md#commit-cleanliness)
- [x] Passing Tests ( Testing removed, but `gulp build` runs correctly. )

### CODE REVIEW

**Comment by drorn-aprcd** [comment]
please, someone, resolve this PR

**Comment by refi64** [comment]
https://github.com/kirbyfan64/better-share-button/commit/c49bf2ea7db3e2f38d68de59a1a8d1e504c7d421

**Comment by erwstout** [comment]
@kirbyfan64 whats the difference between your link and the PR I submitted?

**Comment by refi64** [comment]
@erwstout I added it to a fork I made... :D

**Pull request closed without merging**
