### PR TITLE
fixes detection of email network

### PR DESCRIPTION
**Pull request by hongaar**

### CODE REVIEW

**Comment by hhsnopek** [comment]
Waiting to hear back from Travis-ci, I've restarted the tests for it

**Comment by hhsnopek** [comment]
Awesome, are you able to rebase master onto your branch to bring it back up to speed?

**Comment by hongaar** [comment]
Sure, will try to find some time this weekend!

**Comment by hongaar** [comment]
Rebased on top of master.

**Comment by hhsnopek** [comment]
cc #260

**Comment by hhsnopek** [comment]
confirmed via mobile safari/chrome - working fix!

**Pull request merged**
